### ISSUE TITLE
Spring integration testing not working

### ISSUE THREAD

**Issue by ukjbrown** [jsevellec/cassandra-unit#146] opened 2015-10-15 11:14 UTC
There doesn't appear to be any documentation for using the CassandraUnitDependencyInjectionIntegrationTestExecutionListener and DependencyInjectionTestExecutionListener, but I proceeded to try to use them based on examples;

```java
@TestExecutionListeners(
        listeners = {
                CassandraUnitDependencyInjectionIntegrationTestExecutionListener.class,
                DependencyInjectionTestExecutionListener.class
        },
        mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS
)
@CassandraDataSet(value = "cql/schema.cql", keyspace = "test")
@EmbeddedCassandra(configuration = "cassandra-test.yaml")
public class AbstractCassandraIntegrationTest extends AbstractIntegrationTest {
  //...
}
```

However, I receive the following Exception when the test runs;

```
2015-10-15 12:09:14:572 +0100 [main] INFO com.datastax.driver.core.Cluster - New Cassandra host localhost/127.0.0.1:9142 added

java.lang.NoSuchMethodError: com.datastax.driver.core.Cluster$Builder.addContactPoints(Ljava/lang/String;)Lcom/datastax/driver/core/Cluster$Builder;
	at org.cassandraunit.spring.AbstractCassandraUnitTestExecutionListener.startServer(AbstractCassandraUnitTestExecutionListener.java:63)
	at org.cassandraunit.spring.CassandraUnitDependencyInjectionIntegrationTestExecutionListener.beforeTestClass(CassandraUnitDependencyInjectionIntegrationTestExecutionListener.java:21)
	at org.springframework.test.context.TestContextManager.beforeTestClass(TestContextManager.java:179)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:60)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
```

**Comment by Augi** [comment] 2015-10-15 12:29
It looks like you are using different version of `cassandra-driver-core` than `cassandra-unit` does. Can you confirm that, please?

**Comment by ukjbrown** [comment] 2015-10-15 13:18
Hmm, I haven't explicitly defined the cassandra-driver-core dependency, but it could possibly be coming from spring-data-cassandra? I've tried with spring-data-cassandra 1.2.0 and 1.3.0 and neither appear to work.

**Comment by ukjbrown** [comment] 2015-10-15 13:34
Adding a specific dependency on 2.1.7.1 seems to have got rid of the Exception, but its now failing to load the dataset.

The following manual initialization works;
```java
// Start the embedded cassandra
public void startServer() throws Exception {
        EmbeddedCassandraServerHelper.startEmbeddedCassandra("cassandra-test.yaml", 30000L);
        Cluster cluster = new Cluster.Builder().addContactPoints("127.0.0.1").withPort(9142).build();
        session = cluster.connect();
        CQLDataLoader cqlDataLoader = new CQLDataLoader(session);
        cqlDataLoader.load(new ClassPathCQLDataSet("cql/schema.sql", true, true, "test"));
}
```

However, using the cassandra-unit-spring annotations (as in my first post) produces the following;
```
2015-10-15 14:27:40:317 +0100 [main] WARN org.springframework.test.context.TestContextManager - Caught exception while allowing TestExecutionListener [org.cassandraunit.spring.CassandraUnitDependencyInjectionIntegrationTestExecutionListener@12e61fe6] to process 'before class' callback for test class [class com.test.event.cassandra.MyCassandraIntegrationTest]
org.cassandraunit.dataset.ParseException: Dataset not found
	at org.cassandraunit.dataset.cql.AbstractCQLDataSet.<init>(AbstractCQLDataSet.java:39)
	at org.cassandraunit.dataset.cql.ClassPathCQLDataSet.<init>(ClassPathCQLDataSet.java:34)
	at org.cassandraunit.spring.AbstractCassandraUnitTestExecutionListener.startServer(AbstractCassandraUnitTestExecutionListener.java:70)
	at org.cassandraunit.spring.CassandraUnitDependencyInjectionIntegrationTestExecutionListener.beforeTestClass(CassandraUnitDependencyInjectionIntegrationTestExecutionListener.java:21)
	at org.springframework.test.context.TestContextManager.beforeTestClass(TestContextManager.java:179)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:60)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)

```

**Comment by dmitry-vasilyuk** [comment] 2016-01-20 10:29
I have the same exception as described above.

My configuration:

Java test class contains the following annotations:

@RunWith(SpringJUnit4ClassRunner.class)
@TestExecutionListeners({DependencyInjectionTestExecutionListener.class})
@TestExecutionListeners({CassandraUnitDependencyInjectionIntegrationTestExecutionListener.class, DependencyInjectionTestExecutionListener.class})
@CassandraDataSet(value = {"cql/create_keyspaces.cql", "cql/create_tables.cql"})
@ContextConfiguration(classes = {CqlTemplateConfiguration.class}, loader = AnnotationConfigContextLoader.class)
@EmbeddedCassandra(timeout = 30000L)

pom.xml contains the following dependencies:
```
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-cassandra</artifactId>
    <version>1.3.2.RELEASE</version>
    <exclusions>
      <exclusion>
        <groupId>org.cassandraunit</groupId>
          <artifactId>cassandra-unit</artifactId>
      </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.cassandraunit</groupId>
    <artifactId>cassandra-unit-spring</artifactId>
    <version>2.2.2.1</version>
</dependency>
```

**Comment by MALPI** [comment] 2016-02-02 08:56
Same issue here, I am using the datastax java driver, which has a dependency to `cassandra-diver-core:3.0.0`.

**Comment by cosh** [comment] 2016-02-12 13:30
Same here

**Comment by nilsonfreitas** [comment] 2016-02-15 01:58
I have the same issue.... My env is the following:

- Apache cassandra version **3.3**.
- Driver: com.datastax.cassandra:cassandra-driver-core:3.0.0
- Unit: org.cassandraunit:cassandra-unit:2.2.2.1

Is cassandra unit **2.2.2.1** compatible with datastax **3.0.0** driver? I believe the issue is here...

**Comment by nilsonfreitas** [comment] 2016-02-15 03:07
I've checked Is cassandra unit **2.2.2.1** dependencies and seems it uses an older version of datastax  driver:

<cu.cassandra.driver.version>2.1.9</cu.cassandra.driver.version>

This is why I was getting the same exception...

**Comment by MALPI** [comment] 2016-03-24 12:29
Duplicate of #166

**Closed** 2016-03-24 13:02 UTC
