### ISSUE TITLE
Incompatibilty between DataStax cassandra driver and cassandra-unit

### ISSUE THREAD

**Issue by davidsloan-eduserv** [jsevellec/cassandra-unit#129] opened 2015-06-29 12:37 UTC
I've been trying to add some coverage of our Cassandra code.  We've using datastax cassandra 2.2.0-rc1.

On start-up I'm seeing this:

 13:15:30.635 [SharedPool-Worker-1] ERROR Message [538] - Unexpected exception during request; channel = [id: 0x76adfe6e, /127.0.0.1:37079 => /127.0.0.1:9142]
io.netty.handler.codec.DecoderException: org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version: 4
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:346) ~[netty-codec-4.0.27.Final.jar:4.0.27.Final]
    at ...

Can Cassandra unit be updated to support this version of the datastax driver?

Please let me know if you need any more information about this issue.

**Comment by jsevellec** [comment] 2015-09-08 19:08
I'm currently working to try to make cassandra-unit working using cassandra 2.2

**Comment by mortias** [comment] 2015-09-16 14:21
we experience some sort of same issue? is it related?
our applications use apache-cassandra-2.1.6 but in the logs i see apache-cassandra-2.1.4

>16/09/2015 15:41:32,101 xxx ERROR  CAS [SharedPool-Worker-2] - - - org.apache.cassandra.transport.Message - - - Message.java:538 Unexpected exception during request; channel = [id: 0x3bc3eb38, /xxx:60105 => /xxxx:9042]
io.netty.handler.codec.DecoderException: org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version: 22
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]
Caused by: org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version: 22
        at org.apache.cassandra.transport.Frame$Decoder.decode(Frame.java:184) ~[apache-cassandra-2.1.4.jar:2.1.4]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
        ... 10 common frames omitted

**Comment by haribachala** [comment] 2016-08-25 10:57
Hi @jsevellec 

Is cassandra-unit updated to use  V4 protocol ?

**Comment by jsevellec** [comment] 2019-10-12 09:06
closing the issue as it's now fixed

**Closed by jsevellec** 2019-10-12 09:06 UTC
