### ISSUE TITLE
EmbeddedCassandra cannot start with openj9

### ISSUE THREAD

**Issue by ryoheinagao** [jsevellec/cassandra-unit#295] opened 2019-07-13 05:55 UTC
Hi, thanks for useful tools for testing Cassandra. 
I found a bug related to jamm's version.

EmbeddedCassandra cannot start with openj9. But it works fine under the same version of OpenJDK HostSpot. I think it is a bug caused by jamm version. The same issue was reported at [here](https://github.com/jbellis/jamm/issues/33). Please verify its version used in cassandra-unit.

The error log is here.  
```
java.lang.ExceptionInInitializerError
    at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148)
    at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137)
    at org.github.jamm.MemoryMeter.measure(MemoryMeter.java:178)
    at org.apache.cassandra.utils.ObjectSizes.measure(ObjectSizes.java:163)
    at org.apache.cassandra.utils.ObjectSizes.<clinit>(ObjectSizes.java:39)
    at org.apache.cassandra.dht.Murmur3Partitioner.<clinit>(Murmur3Partitioner.java:46)
    at java.lang.Class.forNameImpl(Native Method)
    at java.lang.Class.forName(Class.java:333)
    at org.apache.cassandra.utils.FBUtilities.classForName(FBUtilities.java:536)
    at org.apache.cassandra.utils.FBUtilities.instanceOrConstruct(FBUtilities.java:552)
    at org.apache.cassandra.utils.FBUtilities.newPartitioner(FBUtilities.java:502)
    at org.apache.cassandra.utils.FBUtilities.newPartitioner(FBUtilities.java:488)
    at org.apache.cassandra.config.DatabaseDescriptor.applyPartitioner(DatabaseDescriptor.java:998)
    at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:318)
    at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:148)
    at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:132)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:145)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:110)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:90)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:82)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:78)

~omitted~

Caused by: java.lang.NumberFormatException: For input string: "v0"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at org.github.jamm.MemoryLayoutSpecification.getEffectiveMemoryLayoutSpecification(MemoryLayoutSpecification.java:190)
    at org.github.jamm.MemoryLayoutSpecification.<clinit>(MemoryLayoutSpecification.java:31)
    ... 38 more
```

**Comment by jsevellec** [comment] 2019-10-12 08:59
duplicate of #249

**Closed by jsevellec** 2019-10-12 08:59 UTC
Labels: need investigation
