### ISSUE TITLE
Gradle build and maven build generates NoHostAvailableException

### ISSUE THREAD

**Issue by pavanraotk** [jsevellec/cassandra-unit#158] opened 2015-12-18 02:20 UTC
Hi All,

We are using embeddedCassandra in our test code. We have multiple tests(for each entity, we have a test code with embeddedCassandra).

Embedded cassandra version:

testCompile 'org.cassandraunit:cassandra-unit-spring:2.1.9.2'

Pre-test class annotations below:

@RunWith(SpringJUnit4ClassRunner.class)
@TestExecutionListeners({
        CassandraUnitTestExecutionListener.class,
        DependencyInjectionTestExecutionListener.class })
@CassandraDataSet(value = { Constants.XXX_CQL })
@EmbeddedCassandra
@ContextConfiguration(locations = Constants.APPLICATION_CONTEXT_PATH)
...

If we run the test individually, it works fine. But when we do a gradle build, or a maven build in Jenkins machine, we get the exception below:

```
java.lang.IllegalStateException at DatabaseConnectorImplTest.java:42
com.datastax.driver.core.exceptions.NoHostAvailableException
    Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException
```

So, the issue for us is being caused because, the test code for one unit test class runs fine, but before the second unit test runs, the embedded cassandra started by the previous class is not closed yet. This makes the port not available and hence we get a NoHostAvailableException(the port 9142 is obviously not available) and hence the error.

I tried using the EmbeddedCassandraServerHelper to start and stop in my code @BeforeClass and @AfterClass. Yet, I still get the same error.

It's very similar to https://github.com/jsevellec/cassandra-unit/issues/154, but for us it is not random, it is in all the builds at Jenkins(tried both maven and gradle). 

Kindly help us in this issue.

Warm regards,
Pavan

**Comment by jamesoliverband** [comment] 2016-01-05 19:43
Did you try to increase timeout? 

@EmbeddedCassandra(timeout = 30000L)

**Comment by pavanraotk2** [comment] 2016-01-06 04:54
James,

I tried that now, it works. I will test it on Jenkins in a few hours, once done, we can actually close this issue :). 

Thanks for the help.

Warm regards,
Pavan

**Comment by jamesoliverband** [comment] 2016-01-06 18:25
Great it works out for you!
May I ask you for my own issue which spring-data-cassandra version you use? 

Thanks in advance!

**Comment by pavanraotk2** [comment] 2016-01-07 04:22
I am using the version of 2.2.2.1 of cassandra-unit-spring.

For the actual DB interaction, we use cassandra-driver-mapping of 2.1.9, since it's more of a POJO kind which looks a lot similar to JPA, not spring-data-cassandra(somehow we didn't want to depend on spring-data for cassandra, not my decision).

**Comment by pavanraotk2** [comment] 2016-01-12 10:00
@jamesoliverband : I am not sure this is working, the same issue is turning up(there was a problem in Jenkins and hence I couldn't test it).

java.lang.IllegalStateException at DatabaseConnectorImplTest.java:42
com.datastax.driver.core.exceptions.NoHostAvailableException
    Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException

**Closed** 2019-10-16 07:04 UTC
