### ISSUE TITLE
Support for non-anonymous connection

### ISSUE THREAD

**Issue by rebrendler** [jsevellec/cassandra-unit#229] opened 2017-04-03 14:01 UTC
In recent versions of Cassandra, calling any methods that deal with roles/users without authorization enabled results in the following error:

`com.datastax.driver.core.exceptions.UnauthorizedException: You have to be logged in and not anonymous to perform this request`

If I start cassandra-unit with a yaml configuration file that enables authorization, I get the following:

`com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host localhost/127.0.0.1:57395: Host localhost/127.0.0.1:57395 requires authentication, but no authenticator found in Cluster configuration`

We need to enable the standard cassandra/cassandra credentials when configuring the cassandra-unit cluster.  If authentication is not enabled they will be ignored, and things will work as they do today.  If authentication is enabled, however, we will be able to execute non-anonymous CQL statements.

**Comment by JCL38-ORANGE** [comment] 2017-08-23 10:19
Hello,

I am facing with this problem. My application needs to have integration tests involving cassandra role and permissions. It is not possible with the current release of cassandra unit.
Is there a workaround ?
Do you plan a release to support this enhancement ?
Thanks and regards,

**Comment by jsevellec** [comment] 2019-10-15 15:35
duplicate of #245

**Closed by jsevellec** 2019-10-15 15:35 UTC
